### ISSUE TITLE
Add reference method

### ISSUE THREAD

**Issue by kadirzengin215** [kadirzengin215/php-arr#4]
### Todos

- [x] Create reference method tests
- [x] Add reference method in ArrInterface.php
- [x] İmplement reference method in Arr.php class from ArrInterface.php
- [x] Run pest,phpstan and pint tests

### Usage
```php
<?php

use KadirZengin215\ArrayRecursiveReference\Arr;

$array = [
    'message' => 'Hello Wold',
    'app' => [
        'name' => 'PHP Arr',
        'url'  => 'localhost'
    ]
];

$messageReference = &Arr::reference($array,'message');

$appReference = &Arr::reference($array,'app');

$nameReference = &Arr::reference($array,'app.name');
```
