### ISSUE TITLE
Add get mehod

### ISSUE THREAD

**Issue by kadirzengin215** [kadirzengin215/php-arr#5]
### Todos
- [x] Create get method tests
- [x] Add get method in ArrInterface.php
- [x] İmplement get method in Arr.php class from ArrInterface.php
- [x] Run pest,phpstan and pint tests

### Usage
```php
<?php

use KadirZengin215\ArrayRecursiveReference\Arr;

$array = [
    'message' => 'Hello World'
];

/*
| Let's retrieve the value of the element with the 'message' key
| from a one-dimensional array.
*/
Arr::get($array,'message');

/*
| If the specified keyword is not present in the array, we can specify
| a custom return value; it defaults to returning null
*/
Arr::get($array,'notexists',false);
```
### Multidimensional arrays
```php
<?php

use KadirZengin215\ArrayRecursiveReference\Arr;

$array = [
    'app' => [
        'name' => 'PHP Arr',
        'url'  => 'localhost'
    ]
];

/*
| Let's retrieve the value of the element with the 'message' key
| from array.
*/
Arr::get($array,'app.name');

/*
| If the specified keyword is not present in the array, we can specify
| a custom return value; it defaults to returning null
*/
Arr::get($array,'app.notexists',false);
```
