### ISSUE TITLE
Add set method

### ISSUE THREAD

**Issue by kadirzengin215** [kadirzengin215/php-arr#6]
### Todos
- [ ] Create set method tests
- [ ] Add set method in ArrInterface.php
- [ ] İmplement set method in Arr.php class from ArrInterface.php
- [ ] Run pest,phpstan and pint tests

## Usage

```php
<?php

use KadirZengin215\ArrayRecursiveReference\Arr;

$array = [
    'message' => 'Hello World'
];

/*
| Let's update the value of the element with the 'message' key in
| a one-dimensional array to 'Hello Universe'.
*/
Arr::set($array,'message','Hello Universe');

/* And our array should now look like this:
[
    'message' => 'Hello Universe'
];
*/

/*
| Let's add a new element with the key 'status' and the value (200) to
| our array.
*/
Arr::set($array,'status',200);

/* And our array should now look like this:
[
    'message' => 'Hello World',
    'status'  => 200
];
*/
```
