### ISSUE TITLE
Add has methods

### ISSUE THREAD

**Issue by kadirzengin215** [kadirzengin215/php-arr#7]
### Todos
- [ ] Create has method tests
- [ ] Add has method in ArrInterface.php
- [ ] İmplement has method in Arr.php class from ArrInterface.php
- [ ] Create hasAll method tests
- [ ] Add hasAll method in ArrInterface.php
- [ ] İmplement hasAll method in Arr.php class from ArrInterface.php
- [ ] Create hasAny method tests
- [ ] Add hasAny method in ArrInterface.php
- [ ] İmplement hasAny method in Arr.php class from ArrInterface.php
- [ ] Run pest,phpstan and pint tests

## Usage

```php
<?php

use KadirZengin215\ArrayRecursiveReference\Arr;

$array = [
    'message' => 'Hello World'
];

/*
| Let's check if there is an element with the key 'message' in our array.
*/
Arr::has($array,'message');

/*
| Also we can check whether multiple elements exist.
*/

/*
| If any of the specified elements is not present, it returns a (false) value
*/
Arr::hasAll($array,'message','notexists');

/*
| If any of the specified keywords is present, it returns a (true) value.
*/
Arr::hasAny($array,'message','notexists');
```
