### ISSUE TITLE
Add push mtehod

### ISSUE THREAD

**Issue by kadirzengin215** [kadirzengin215/php-arr#8]
### Todos
- [ ] Create push method tests
- [ ] Add push method in ArrInterface.php
- [ ] İmplement push method in Arr.php class from ArrInterface.php
- [ ] Run pest,phpstan and pint tests

## Usage

```php
<?php

use KadirZengin215\ArrayRecursiveReference\Arr;

$array = [
    'message' => 'Hello World'
];

/*
| Now let's add new elements to the array in numerical order.
*/
Arr::push($array,['First element','Second element']);

/* And our array should now look like this:
[
    'message' => 'Hello World',
    0 => 'First Element',
    1 => 'Second Element'
];
*/
```
